### ISSUE TITLE
Error when running scripts/create_semantic_maps.py

### ISSUE THREAD

**Issue by dachii-azm** [srama2512/PONI#3]
I tried to create a semantic map using matterport3d, but I got error for both bias-compressed version and non-basis compressed version.

command is ths.
```ACTIVE_DATASET="mp3d" python scripts/create_semantic_maps.py```

Error log by bias-compressed version is this.
```
failed to load image!
Traceback (most recent call last):
  File "/home/dachii/anaconda3/envs/poni2/lib/python3.8/site-packages/trimesh/exchange/gltf.py", line 1149, in _parse_materials
    images[i] = PIL.Image.open(util.wrap_as_stream(blob))
  File "/home/dachii/anaconda3/envs/poni2/lib/python3.8/site-packages/PIL/Image.py", line 3147, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7f78d22dd540>
failed to load image!
Traceback (most recent call last):
  File "/home/dachii/anaconda3/envs/poni2/lib/python3.8/site-packages/trimesh/exchange/gltf.py", line 1149, in _parse_materials
    images[i] = PIL.Image.open(util.wrap_as_stream(blob))
  File "/home/dachii/anaconda3/envs/poni2/lib/python3.8/site-packages/PIL/Image.py", line 3147, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7f78d22dd540>
failed to load image!
Traceback (most recent call last):
  File "/home/dachii/anaconda3/envs/poni2/lib/python3.8/site-packages/trimesh/exchange/gltf.py", line 1149, in _parse_materials
    images[i] = PIL.Image.open(util.wrap_as_stream(blob))
  File "/home/dachii/anaconda3/envs/poni2/lib/python3.8/site-packages/PIL/Image.py", line 3147, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7f78d22dd540>
failed to load image!
Traceback (most recent call last):
  File "/home/dachii/anaconda3/envs/poni2/lib/python3.8/site-packages/trimesh/exchange/gltf.py", line 1149, in _parse_materials
    images[i] = PIL.Image.open(util.wrap_as_stream(blob))
  File "/home/dachii/anaconda3/envs/poni2/lib/python3.8/site-packages/PIL/Image.py", line 3147, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7f78d22dd540>
failed to load image!
Traceback (most recent call last):
  File "/home/dachii/anaconda3/envs/poni2/lib/python3.8/site-packages/trimesh/exchange/gltf.py", line 1149, in _parse_materials
    images[i] = PIL.Image.open(util.wrap_as_stream(blob))
  File "/home/dachii/anaconda3/envs/poni2/lib/python3.8/site-packages/PIL/Image.py", line 3147, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7f78d22dd540>
failed to load image!
Traceback (most recent call last):
  File "/home/dachii/anaconda3/envs/poni2/lib/python3.8/site-packages/trimesh/exchange/gltf.py", line 1149, in _parse_materials
    images[i] = PIL.Image.open(util.wrap_as_stream(blob))
  File "/home/dachii/anaconda3/envs/poni2/lib/python3.8/site-packages/PIL/Image.py", line 3147, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7f78d22dd540>
failed to load image!
Traceback (most recent call last):
  File "/home/dachii/anaconda3/envs/poni2/lib/python3.8/site-packages/trimesh/exchange/gltf.py", line 1149, in _parse_materials
    images[i] = PIL.Image.open(util.wrap_as_stream(blob))
  File "/home/dachii/anaconda3/envs/poni2/lib/python3.8/site-packages/PIL/Image.py", line 3147, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7f78d22dd540>
failed to load image!
Traceback (most recent call last):
  File "/home/dachii/anaconda3/envs/poni2/lib/python3.8/site-packages/trimesh/exchange/gltf.py", line 1149, in _parse_materials
    images[i] = PIL.Image.open(util.wrap_as_stream(blob))
  File "/home/dachii/anaconda3/envs/poni2/lib/python3.8/site-packages/PIL/Image.py", line 3147, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7f78d22dd540>
failed to load image!
Traceback (most recent call last):
  File "/home/dachii/anaconda3/envs/poni2/lib/python3.8/site-packages/trimesh/exchange/gltf.py", line 1149, in _parse_materials
    images[i] = PIL.Image.open(util.wrap_as_stream(blob))
  File "/home/dachii/anaconda3/envs/poni2/lib/python3.8/site-packages/PIL/Image.py", line 3147, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7f78d22dd540>
failed to load image!
Traceback (most recent call last):
  File "/home/dachii/anaconda3/envs/poni2/lib/python3.8/site-packages/trimesh/exchange/gltf.py", line 1149, in _parse_materials
    images[i] = PIL.Image.open(util.wrap_as_stream(blob))
  File "/home/dachii/anaconda3/envs/poni2/lib/python3.8/site-packages/PIL/Image.py", line 3147, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7f78d22dd540>
failed to load image!
Traceback (most recent call last):
  File "/home/dachii/anaconda3/envs/poni2/lib/python3.8/site-packages/trimesh/exchange/gltf.py", line 1149, in _parse_materials
    images[i] = PIL.Image.open(util.wrap_as_stream(blob))
  File "/home/dachii/anaconda3/envs/poni2/lib/python3.8/site-packages/PIL/Image.py", line 3147, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7f78d22dd540>
failed to load image!
Traceback (most recent call last):
  File "/home/dachii/anaconda3/envs/poni2/lib/python3.8/site-packages/trimesh/exchange/gltf.py", line 1149, in _parse_materials
    images[i] = PIL.Image.open(util.wrap_as_stream(blob))
  File "/home/dachii/anaconda3/envs/poni2/lib/python3.8/site-packages/PIL/Image.py", line 3147, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7f78d22dd540>
failed to load image!
Traceback (most recent call last):
  File "/home/dachii/anaconda3/envs/poni2/lib/python3.8/site-packages/trimesh/exchange/gltf.py", line 1149, in _parse_materials
    images[i] = PIL.Image.open(util.wrap_as_stream(blob))
  File "/home/dachii/anaconda3/envs/poni2/lib/python3.8/site-packages/PIL/Image.py", line 3147, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7f78d22dd540>
failed to load image!
Traceback (most recent call last):
  File "/home/dachii/anaconda3/envs/poni2/lib/python3.8/site-packages/trimesh/exchange/gltf.py", line 1149, in _parse_materials
    images[i] = PIL.Image.open(util.wrap_as_stream(blob))
  File "/home/dachii/anaconda3/envs/poni2/lib/python3.8/site-packages/PIL/Image.py", line 3147, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7f78d22dd540>
failed to load image!
Traceback (most recent call last):
  File "/home/dachii/anaconda3/envs/poni2/lib/python3.8/site-packages/trimesh/exchange/gltf.py", line 1149, in _parse_materials
    images[i] = PIL.Image.open(util.wrap_as_stream(blob))
  File "/home/dachii/anaconda3/envs/poni2/lib/python3.8/site-packages/PIL/Image.py", line 3147, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7f78d22dd540>
failed to load image!
Traceback (most recent call last):
  File "/home/dachii/anaconda3/envs/poni2/lib/python3.8/site-packages/trimesh/exchange/gltf.py", line 1149, in _parse_materials
    images[i] = PIL.Image.open(util.wrap_as_stream(blob))
  File "/home/dachii/anaconda3/envs/poni2/lib/python3.8/site-packages/PIL/Image.py", line 3147, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7f78d22dd540>
failed to load image!
Traceback (most recent call last):
  File "/home/dachii/anaconda3/envs/poni2/lib/python3.8/site-packages/trimesh/exchange/gltf.py", line 1149, in _parse_materials
    images[i] = PIL.Image.open(util.wrap_as_stream(blob))
  File "/home/dachii/anaconda3/envs/poni2/lib/python3.8/site-packages/PIL/Image.py", line 3147, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7f78d22dd540>
failed to load image!
Traceback (most recent call last):
  File "/home/dachii/anaconda3/envs/poni2/lib/python3.8/site-packages/trimesh/exchange/gltf.py", line 1149, in _parse_materials
    images[i] = PIL.Image.open(util.wrap_as_stream(blob))
  File "/home/dachii/anaconda3/envs/poni2/lib/python3.8/site-packages/PIL/Image.py", line 3147, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7f78d22dd540>
failed to load image!
Traceback (most recent call last):
  File "/home/dachii/anaconda3/envs/poni2/lib/python3.8/site-packages/trimesh/exchange/gltf.py", line 1149, in _parse_materials
    images[i] = PIL.Image.open(util.wrap_as_stream(blob))
  File "/home/dachii/anaconda3/envs/poni2/lib/python3.8/site-packages/PIL/Image.py", line 3147, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7f78d22dd540>
failed to load image!
Traceback (most recent call last):
  File "/home/dachii/anaconda3/envs/poni2/lib/python3.8/site-packages/trimesh/exchange/gltf.py", line 1149, in _parse_materials
    images[i] = PIL.Image.open(util.wrap_as_stream(blob))
  File "/home/dachii/anaconda3/envs/poni2/lib/python3.8/site-packages/PIL/Image.py", line 3147, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7f78d22dd540>
failed to load image!
Traceback (most recent call last):
  File "/home/dachii/anaconda3/envs/poni2/lib/python3.8/site-packages/trimesh/exchange/gltf.py", line 1149, in _parse_materials
    images[i] = PIL.Image.open(util.wrap_as_stream(blob))
  File "/home/dachii/anaconda3/envs/poni2/lib/python3.8/site-packages/PIL/Image.py", line 3147, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7f78d22dd540>
failed to load image!
Traceback (most recent call last):
  File "/home/dachii/anaconda3/envs/poni2/lib/python3.8/site-packages/trimesh/exchange/gltf.py", line 1149, in _parse_materials
    images[i] = PIL.Image.open(util.wrap_as_stream(blob))
  File "/home/dachii/anaconda3/envs/poni2/lib/python3.8/site-packages/PIL/Image.py", line 3147, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7f78d22dd540>
failed to load image!
Traceback (most recent call last):
  File "/home/dachii/anaconda3/envs/poni2/lib/python3.8/site-packages/trimesh/exchange/gltf.py", line 1149, in _parse_materials
    images[i] = PIL.Image.open(util.wrap_as_stream(blob))
  File "/home/dachii/anaconda3/envs/poni2/lib/python3.8/site-packages/PIL/Image.py", line 3147, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7f78d22dd540>
I0820 08:20:27.053874 125483 Simulator.cpp:54] Deconstructing Simulator
  0%|                                                                                                   | 0/1 [00:43<?, ?it/s]I0820 08:20:27.053992 125483 Simulator.cpp:54] Deconstructing Simulator

multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/dachii/anaconda3/envs/poni2/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/dachii/workspace/Project/PONI/scripts/create_semantic_maps.py", line 262, in _aux_fn
    return inputs[0](*inputs[1:])
  File "/home/dachii/workspace/Project/PONI/scripts/create_semantic_maps.py", line 236, in extract_scene_point_clouds
    per_floor_wall_pc = extract_wall_point_clouds(
  File "/home/dachii/workspace/Project/PONI/scripts/create_semantic_maps.py", line 309, in extract_wall_point_clouds
    scene = trimesh.load(glb_path)
  File "/home/dachii/anaconda3/envs/poni2/lib/python3.8/site-packages/trimesh/exchange/load.py", line 127, in load
    loaded = load_mesh(file_obj,
  File "/home/dachii/anaconda3/envs/poni2/lib/python3.8/site-packages/trimesh/constants.py", line 153, in timed
    result = method(*args, **kwargs)
  File "/home/dachii/anaconda3/envs/poni2/lib/python3.8/site-packages/trimesh/exchange/load.py", line 209, in load_mesh
    results = mesh_loaders[file_type](file_obj,
  File "/home/dachii/anaconda3/envs/poni2/lib/python3.8/site-packages/trimesh/exchange/gltf.py", line 372, in load_glb
    kwargs = _read_buffers(header=header,
  File "/home/dachii/anaconda3/envs/poni2/lib/python3.8/site-packages/trimesh/exchange/gltf.py", line 1333, in _read_buffers
    materials = _parse_materials(
  File "/home/dachii/anaconda3/envs/poni2/lib/python3.8/site-packages/trimesh/exchange/gltf.py", line 1176, in _parse_materials
    idx = header["textures"][v["index"]]["source"]
KeyError: 'source'
"""
```

Error log by non-bias-compressed version is this.

```
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/dachii/anaconda3/envs/poni2/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/dachii/workspace/Project/PONI/scripts/create_semantic_maps.py", line 262, in _aux_fn
    return inputs[0](*inputs[1:])
  File "/home/dachii/workspace/Project/PONI/scripts/create_semantic_maps.py", line 236, in extract_scene_point_clouds
    per_floor_wall_pc = extract_wall_point_clouds(
  File "/home/dachii/workspace/Project/PONI/scripts/create_semantic_maps.py", line 309, in extract_wall_point_clouds
    scene = trimesh.load(glb_path)
  File "/home/dachii/anaconda3/envs/poni2/lib/python3.8/site-packages/trimesh/exchange/load.py", line 127, in load
    loaded = load_mesh(file_obj,
  File "/home/dachii/anaconda3/envs/poni2/lib/python3.8/site-packages/trimesh/constants.py", line 153, in timed
    result = method(*args, **kwargs)
  File "/home/dachii/anaconda3/envs/poni2/lib/python3.8/site-packages/trimesh/exchange/load.py", line 209, in load_mesh
    results = mesh_loaders[file_type](file_obj,
  File "/home/dachii/anaconda3/envs/poni2/lib/python3.8/site-packages/trimesh/exchange/gltf.py", line 372, in load_glb
    kwargs = _read_buffers(header=header,
  File "/home/dachii/anaconda3/envs/poni2/lib/python3.8/site-packages/trimesh/exchange/gltf.py", line 1333, in _read_buffers
    materials = _parse_materials(
  File "/home/dachii/anaconda3/envs/poni2/lib/python3.8/site-packages/trimesh/exchange/gltf.py", line 1140, in _parse_materials
    blob = _uri_to_bytes(uri=img['uri'], resolver=resolver)
  File "/home/dachii/anaconda3/envs/poni2/lib/python3.8/site-packages/trimesh/exchange/gltf.py", line 403, in _uri_to_bytes
    return resolver[uri]
TypeError: 'NoneType' object is not subscriptable
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "scripts/create_semantic_maps.py", line 736, in <module>
    _ = list(tqdm.tqdm(pool.imap(_aux_fn, inputs), total=len(inputs)))
  File "/home/dachii/anaconda3/envs/poni2/lib/python3.8/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/home/dachii/anaconda3/envs/poni2/lib/python3.8/multiprocessing/pool.py", line 868, in next
    raise value
TypeError: 'NoneType' object is not subscriptable
```

How do I solve this?

===my environment===
Ubuntu20.04
GPU: RTX3080
CUDA: 11.3.1
Pytorch: 1.10

**Comment by pioneer-innovation** [comment]
I meet the same bug. Have you solved it？

**Comment by srama2512** [comment]
@dachii-azm  @pioneer-innovation  - This seems to be an issue with the trimesh installation. Perhaps you could raise an issue on that repo? I did not encounter this error before. If you use non-basis compressed meshes, the code should work as expected.
