### ISSUE TITLE
Installation Issue on Install dependencies Part : Could not build wheels for torch-scatter,

### ISSUE THREAD

**Issue by anilkusc** [srama2512/PONI#35]
Hello. I am trying to follow up installation on Readme.
I could process successfully until  Install dependencies part.
I am using Ubuntu 24.04 LTS.
When I try to copy Install dependencies part and and run I got following logs(Simplified):

> poni) anil@anil-PC:~/Desktop/Projects/PONI/dependencies/habitat-lab$ cd $PONI_ROOT/dependencies/habitat-lab
pip install -r requirements.txt
python setup.py develop --all
cd $PONI_ROOT/dependencies/habitat-sim
pip install -r requirements.txt
python setup.py install --headless --with-cuda
python -m pip install detectron2 -f https://dl.fbaipublicfiles.com/detectron2/wheels/cu102/torch1.9/index.html
pip install torch-scatter -f https://data.pyg.org/whl/torch-1.9.0+cu102.html
cd $PONI_ROOT/dependencies/astar_pycpp && make
Installed /home/anil/Desktop/Projects/PONI/dependencies/habitat-lab
Processing dependencies for habitat==0.2.1
Searching for tensorflow==1.13.1
Reading https://pypi.org/simple/tensorflow/
No local packages or working download links found for tensorflow==1.13.1
error: Could not find suitable distribution for Requirement.parse('tensorflow==1.13.1')
setup.py:419: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  assert StrictVersion(
setup.py:421: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  ) >= StrictVersion("3.6"), "Must use python3.6 or newer"
running install
/home/anil/anaconda3/envs/poni/lib/python3.8/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
/home/anil/anaconda3/envs/poni/lib/python3.8/site-packages/setuptools/_distutils/cmd.py:66: EasyInstallDeprecationWarning: easy_install command is deprecated.
running bdist_egg
running egg_info
writing habitat_sim.egg-info/PKG-INFO
writing dependency_links to habitat_sim.egg-info/dependency_links.txt
writing requirements to habitat_sim.egg-info/requires.txt
writing top-level names to habitat_sim.egg-info/top_level.txt
reading manifest file 'habitat_sim.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
adding license file 'LICENSE'
writing manifest file 'habitat_sim.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
copying examples/settings.py -> build/lib.linux-x86_64-cpython-38/examples
copying habitat_sim/sensors/noise_models/__init__.py -> build/lib.linux-x86_64-cpython-38/habitat_sim/sensors/noise_models
/home/anil/anaconda3/envs/poni/lib/python3.8/site-packages/setuptools/command/build_py.py:207: _Warning: Package 'habitat_sim.sensors.noise_models.data' is absent from the `packages` configuration.
  check.warn(importable)
copying habitat_sim/sensors/noise_models/data/redwood-depth-dist-model.npy -> build/lib.linux-x86_64-cpython-38/habitat_sim/sensors/noise_models/data
running build_ext
Traceback (most recent call last):
  File "setup.py", line 239, in run
    subprocess.check_output([osp.join(CMAKE_BIN_DIR, "cmake"), "--version"])
  File "/home/anil/anaconda3/envs/poni/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/home/anil/anaconda3/envs/poni/lib/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/home/anil/anaconda3/envs/poni/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/anil/anaconda3/envs/poni/lib/python3.8/subprocess.py", line 1720, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'cmake'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "setup.py", line 440, in <module>
    setup(
  File "/home/anil/anaconda3/envs/poni/lib/python3.8/site-packages/setuptools/__init__.py", line 104, in setup
    return distutils.core.setup(**attrs)
  File "/home/anil/anaconda3/envs/poni/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 184, in setup
    return run_commands(dist)
  File "/home/anil/anaconda3/envs/poni/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
    dist.run_commands()
  File "/home/anil/anaconda3/envs/poni/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/home/anil/anaconda3/envs/poni/lib/python3.8/site-packages/setuptools/dist.py", line 967, in run_command
    super().run_command(command)
  File "/home/anil/anaconda3/envs/poni/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/anil/anaconda3/envs/poni/lib/python3.8/site-packages/setuptools/command/install.py", line 87, in run
    self.do_egg_install()
  File "/home/anil/anaconda3/envs/poni/lib/python3.8/site-packages/setuptools/command/install.py", line 139, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/anil/anaconda3/envs/poni/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "/home/anil/anaconda3/envs/poni/lib/python3.8/site-packages/setuptools/dist.py", line 967, in run_command
    super().run_command(command)
  File "/home/anil/anaconda3/envs/poni/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/anil/anaconda3/envs/poni/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 167, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/anil/anaconda3/envs/poni/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 153, in call_command
    self.run_command(cmdname)
  File "/home/anil/anaconda3/envs/poni/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "/home/anil/anaconda3/envs/poni/lib/python3.8/site-packages/setuptools/dist.py", line 967, in run_command
    super().run_command(command)
  File "/home/anil/anaconda3/envs/poni/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/anil/anaconda3/envs/poni/lib/python3.8/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/anil/anaconda3/envs/poni/lib/python3.8/site-packages/setuptools/_distutils/command/install_lib.py", line 110, in build
    self.run_command('build_ext')
  File "/home/anil/anaconda3/envs/poni/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "/home/anil/anaconda3/envs/poni/lib/python3.8/site-packages/setuptools/dist.py", line 967, in run_command
    super().run_command(command)
  File "/home/anil/anaconda3/envs/poni/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "setup.py", line 241, in run
    raise RuntimeError(
RuntimeError: CMake must be installed to build the following extensions: habitat_sim._ext.habitat_sim_bindings
Looking in links: https://dl.fbaipublicfiles.com/detectron2/wheels/cu102/torch1.9/index.html
Looking in links: https://data.pyg.org/whl/torch-1.9.0+cu102.html
Collecting torch-scatter
  Using cached torch_scatter-2.1.2.tar.gz (108 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: torch-scatter
  Building wheel for torch-scatter (setup.py) ... error
  error: subprocess-exited-with-error
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [40 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-38
      creating build/lib.linux-x86_64-cpython-38/torch_scatter
      copying torch_scatter/placeholder.py -> build/lib.linux-x86_64-cpython-38/torch_scatter
      copying torch_scatter/testing.py -> build/lib.linux-x86_64-cpython-38/torch_scatter
      copying torch_scatter/segment_coo.py -> build/lib.linux-x86_64-cpython-38/torch_scatter
      copying torch_scatter/segment_csr.py -> build/lib.linux-x86_64-cpython-38/torch_scatter
      copying torch_scatter/utils.py -> build/lib.linux-x86_64-cpython-38/torch_scatter
      copying torch_scatter/scatter.py -> build/lib.linux-x86_64-cpython-38/torch_scatter
      copying torch_scatter/__init__.py -> build/lib.linux-x86_64-cpython-38/torch_scatter
      creating build/lib.linux-x86_64-cpython-38/torch_scatter/composite
      copying torch_scatter/composite/softmax.py -> build/lib.linux-x86_64-cpython-38/torch_scatter/composite
      copying torch_scatter/composite/std.py -> build/lib.linux-x86_64-cpython-38/torch_scatter/composite
      copying torch_scatter/composite/logsumexp.py -> build/lib.linux-x86_64-cpython-38/torch_scatter/composite
      copying torch_scatter/composite/__init__.py -> build/lib.linux-x86_64-cpython-38/torch_scatter/composite
      running egg_info
      writing torch_scatter.egg-info/PKG-INFO
      writing dependency_links to torch_scatter.egg-info/dependency_links.txt
      writing requirements to torch_scatter.egg-info/requires.txt
      writing top-level names to torch_scatter.egg-info/top_level.txt
      reading manifest file 'torch_scatter.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no previously-included files matching '*' found under directory 'test'
      adding license file 'LICENSE'
      writing manifest file 'torch_scatter.egg-info/SOURCES.txt'
      running build_ext
      building 'torch_scatter._segment_csr_cpu' extension
      creating build/temp.linux-x86_64-cpython-38
      creating build/temp.linux-x86_64-cpython-38/csrc
      creating build/temp.linux-x86_64-cpython-38/csrc/cpu
      gcc -pthread -B /home/anil/anaconda3/envs/poni/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_PYTHON -Icsrc -I/home/anil/anaconda3/envs/poni/lib/python3.8/site-packages/torch/include -I/home/anil/anaconda3/envs/poni/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/anil/anaconda3/envs/poni/lib/python3.8/site-packages/torch/include/TH -I/home/anil/anaconda3/envs/poni/lib/python3.8/site-packages/torch/include/THC -I/home/anil/anaconda3/envs/poni/include/python3.8 -c csrc/cpu/segment_csr_cpu.cpp -o build/temp.linux-x86_64-cpython-38/csrc/cpu/segment_csr_cpu.o -O3 -Wno-sign-compare -DAT_PARALLEL_OPENMP -fopenmp -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -DTORCH_EXTENSION_NAME=_segment_csr_cpu -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
      cc1plus: warning: command-line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
      csrc/cpu/segment_csr_cpu.cpp:6:10: fatal error: ATen/OpMathType.h: No such file or directory
          6 | #include <ATen/OpMathType.h>
            |          ^~~~~~~~~~~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for torch-scatter
  Running setup.py clean for torch-scatter
Failed to build torch-scatter
ERROR: Could not build wheels for torch-scatter, which is required to install pyproject.toml-based projects
g++ astar.cpp -o astar.so -O3 -Wall -shared -fpic

**Comment by coldflsh** [comment]
pip install --no-index torch-scatter -f https://data.pyg.org/whl/torch-1.9.0+cu102.html
